name = "my-portfolio"
pages_build_output_dir = "."
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "portfolio_db"
database_id = "PASTE-YOUR-D1-ID-HERE"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "portfolio-assets"
